export default {
  stepIndicatorSize: 25,
  currentStepIndicatorSize:30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: '#0cafe5',
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: '#0cafe5',
  stepStrokeUnFinishedColor: '#aaaaaa',
  separatorFinishedColor:  '#0cafe5',
  separatorUnFinishedColor: '#aaaaaa',
  stepIndicatorFinishedColor: '#0cafe5',
  stepIndicatorUnFinishedColor: '#ffffff',
  stepIndicatorCurrentColor: '#ffffff',
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 13,
  stepIndicatorLabelCurrentColor: '#0cafe5',
  stepIndicatorLabelFinishedColor: '#ffffff',
  stepIndicatorLabelUnFinishedColor: '#aaaaaa',
  labelColor: '#999999',
  labelSize: 13,
  currentStepLabelColor: '#0cafe5'
}